version: "3.5"

services:

  # Presto

  presto-coordinator:
    image: johannestang/prestodb:326
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config/presto:/opt/presto/etc
    networks:
      - base_net

networks:
  base_net:
    name: bigdatanet
